tosca_definitions_version: cloudify_dsl_1_3

description: >
  Simple blueprint to launch nginx as a "service component"
  Exposes port as a NodePort service with ipv6
  If kubernetes don't have ipv6, service will get ipv4

imports:
  - https://www.getcloudify.org/spec/cloudify/4.5.5/types.yaml
  - plugin:k8splugin?version=>=3.0.0,<4.0.0

node_templates:
  web_server:
    type: dcae.nodes.ContainerizedServiceComponent
    properties:
      service_component_type: 'nginx-web'
      image: nginx
      docker_config:
        healthcheck:
          type: "http"
          endpoint: "/"
        ports:
          - '80:0'
          - concat: ['80:30581']
            ipv6: "Y"
